# Generated by Django 4.2.25 on 2025-10-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when prescription was uploaded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Name of the prescribing doctor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(help_text='Uploaded prescription image', upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Name of the medication', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text="Dosage information (e.g., '500mg', '2 tablets')", max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, help_text="Frequency of medication (e.g., 'twice daily', 'after meals')", max_length=100, null=True)),
                ('prescription', models.ForeignKey(help_text='Parent prescription this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medications.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
    ]
