# Generated by Django 4.2.25 on 2025-10-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('medication_interaction', 'Medication Interaction'), ('dosage_optimization', 'Dosage Optimization'), ('schedule_improvement', 'Schedule Improvement'), ('health_trend', 'Health Trend'), ('compliance_analysis', 'Compliance Analysis'), ('side_effect_warning', 'Side Effect Warning'), ('general_recommendation', 'General Recommendation')], help_text='Type of insight', max_length=50)),
                ('title', models.CharField(help_text='Title of the insight', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the insight')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of recommendations')),
                ('confidence_score', models.FloatField(help_text='Confidence score of the insight (0-1)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the insight is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file that was processed', upload_to='ocr_images/')),
                ('extracted_text', models.TextField(help_text='Text extracted from the image')),
                ('confidence_score', models.FloatField(help_text='Confidence score of the OCR result (0-1)')),
                ('processing_time', models.FloatField(help_text='Time taken to process the image in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OCR Result',
                'verbose_name_plural': 'OCR Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Name of the recognized medication', max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='Dosage information extracted', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='Frequency information extracted', max_length=100)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the recognition (0-1)')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the recognition has been verified by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_recognitions', to='ai.ocrresult')),
            ],
            options={
                'verbose_name': 'Medication Recognition',
                'verbose_name_plural': 'Medication Recognitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
