"""
Models for the ai app.

This module contains Django models for AI-related data.
Defines the structure for OCR results, medication recognition, and AI insights.
"""

from django.db import models
from django.contrib.auth.models import User


class OCRResult(models.Model):
    """
    Model representing OCR (Optical Character Recognition) results.
    
    Stores information about text extracted from images using OCR technology.
    """
    image = models.ImageField(upload_to='ocr_images/', help_text="Image file that was processed")
    extracted_text = models.TextField(help_text="Text extracted from the image")
    confidence_score = models.FloatField(help_text="Confidence score of the OCR result (0-1)")
    processing_time = models.FloatField(help_text="Time taken to process the image in seconds")
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'OCR Result'
        verbose_name_plural = 'OCR Results'
    
    def __str__(self):
        return f"OCR Result - {self.created_at.strftime('%Y-%m-%d %H:%M')}"


class MedicationRecognition(models.Model):
    """
    Model representing AI medication recognition results.
    
    Stores information about medications recognized from OCR text
    using AI/ML algorithms.
    """
    ocr_result = models.ForeignKey(OCRResult, on_delete=models.CASCADE, related_name='medication_recognitions')
    medication_name = models.CharField(max_length=255, help_text="Name of the recognized medication")
    dosage = models.CharField(max_length=100, blank=True, help_text="Dosage information extracted")
    frequency = models.CharField(max_length=100, blank=True, help_text="Frequency information extracted")
    confidence_score = models.FloatField(help_text="Confidence score of the recognition (0-1)")
    is_verified = models.BooleanField(default=False, help_text="Whether the recognition has been verified by user")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Medication Recognition'
        verbose_name_plural = 'Medication Recognitions'
    
    def __str__(self):
        return f"{self.medication_name} - {self.confidence_score:.2f}"


class AIInsight(models.Model):
    """
    Model representing AI-generated insights and recommendations.
    
    Stores insights, recommendations, and analysis generated by AI
    based on user data and medication information.
    """
    INSIGHT_TYPES = [
        ('medication_interaction', 'Medication Interaction'),
        ('dosage_optimization', 'Dosage Optimization'),
        ('schedule_improvement', 'Schedule Improvement'),
        ('health_trend', 'Health Trend'),
        ('compliance_analysis', 'Compliance Analysis'),
        ('side_effect_warning', 'Side Effect Warning'),
        ('general_recommendation', 'General Recommendation'),
    ]
    
    insight_type = models.CharField(max_length=50, choices=INSIGHT_TYPES, help_text="Type of insight")
    title = models.CharField(max_length=255, help_text="Title of the insight")
    description = models.TextField(help_text="Detailed description of the insight")
    recommendations = models.JSONField(default=list, blank=True, help_text="List of recommendations")
    confidence_score = models.FloatField(help_text="Confidence score of the insight (0-1)")
    is_active = models.BooleanField(default=True, help_text="Whether the insight is active")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'AI Insight'
        verbose_name_plural = 'AI Insights'
    
    def __str__(self):
        return f"{self.title} - {self.insight_type}"